[versions]
kotlin = "2.4.20"
coroutines = "1.11.0"
serialization = "1.11.0"
filament-kmp = "0.7.1"
compose-multiplatform = "1.12.1"
ktlint-gradle = "14.2.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
filament = { module = "io.github.erkko68.filament:filament", version.ref = "filament-kmp" }
filamat = { module = "io.github.erkko68.filament:filamat", version.ref = "filament-kmp" }
filament-compose = { module = "io.github.erkko68.filament:filament-compose", version.ref = "filament-kmp" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
