[versions]
kotlin = "2.4.20"
serialization = "1.11.0"
filament-kmp = "0.7.1"
ktlint-gradle = "14.2.0"
detekt = "2.0.0-alpha.6"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
detekt-gradle-plugin = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
filament = { module = "io.github.erkko68.filament:filament", version.ref = "filament-kmp" }
filamat = { module = "io.github.erkko68.filament:filamat", version.ref = "filament-kmp" }
